services:
  jenkins:
    image: jenkins/jenkins:jdk11
    restart: on-failure:10
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      jenkins-setup: 
        condition: service_completed_successfully

  jenkins-setup:
    image: jenkins/jenkins:jdk11
    container_name: jenkins-setup
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./plugin.txt:/tmp/plugin.txt
      - ./backup_dir:/tmp/jenkins_home
      - ./init.sh:/tmp/init.sh
    command: bash /tmp/init.sh

volumes:
  jenkins_home:
